"""empty message

Revision ID: 0884d487c294
Revises: 6f641e2a1e42
Create Date: 2022-01-15 17:10:56.084208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0884d487c294'
down_revision = '6f641e2a1e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_equipments',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('vessel_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_equipments')
    # ### end Alembic commands ###
