"""empty message

Revision ID: 534d40810d20
Revises: da066c65cbf7
Create Date: 2022-01-15 22:30:31.601568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '534d40810d20'
down_revision = 'da066c65cbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_orders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('equipment_code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_code'], ['vessel_equipments.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_orders')
    # ### end Alembic commands ###
