"""empty message

Revision ID: 6f641e2a1e42
Revises: 
Create Date: 2022-01-15 15:56:50.973777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f641e2a1e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vessels', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessels', type_='unique')
    # ### end Alembic commands ###
